# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: df2f7218caf34424224bf34946d75b3efa365429daf102c5b1e366c8a7be2949ee09d1dde909b7f5e0a935b2719f7afa41af5e2d3fe512c61fb79ceab95f5269

test:
  secret_key_base: 4395f120178c4bb76075e66d0ea31c9d098a17c7c61f6391f495af24143162efa3c49e708185a3a34831eb341687f1407237ac5c2db53253f471a05187967208

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
